app:
  build: .
  command: npm start
  environment:
    - PORT
    - POSTGRES_URL
    - REDIS_URL
  links:
    - postgres
    - redis
  ports:
    - 8080:80

postgres:
  image: convox/postgres
  ports:
    - 5432
  volumes:
    - /data/postgresql/data:/var/lib/postgresql/data

redis:
  image: convox/redis
  ports:
    - 6379
